on: [push, pull_request]

name: main workflow

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_OPTIONS: --max_old_space_size=4096


jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Compiler Installations
      uses: actions/cache@v3
      with:
        path: |
          ~/.solcx
          ~/.vvm
        key: compiler-cache

    - name: Setup Node.js
      uses: actions/setup-node@v3

    - name: Install Ganache
      run: npm install -g ganache

    - name: Setup Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install Requirements
      run: |
        pip install eth-brownie
        pip install vyper

    - name: Run Tests
      run: brownie test